import { LANGUAGES } from "./i18n";
import type { AppLanguage } from "./types";

const languageName = (language: AppLanguage) => LANGUAGES.find(item => item.code === language)?.label ?? "English";
export const generatePrompt = (language: AppLanguage, size: number, known: unknown, targets: unknown) => `Generate exactly ${size} unique sentences.\nKnown vocabulary (JSON): ${JSON.stringify(known)}\nPriority vocabulary (JSON): ${JSON.stringify(targets)}\nUse ONLY complete entries from known vocabulary, including all function words. Separate every vocabulary item in chinese with one ASCII space; preserve multi-character entries. Prioritize targets, maximize diversity, and vary grammar. Every sentence must express one clear, plausible idea. The russian field is a legacy field name: always put a natural ${languageName(language)} translation in it. For every sentence, provide a concise grammarPattern label identifying its primary Mandarin structure. Return JSON only: {"sentences":[{"chinese":"我 今天 回 家","pinyin":"Wǒ jīntiān huí jiā.","russian":"translation in ${languageName(language)}","grammarPattern":"S + Time + V + O"}]}`;
export const evaluatePrompt = (language: AppLanguage, chinese: string, pinyin: string, translation: string, answer: string) => `Evaluate a learner's ${languageName(language)} translation. Accept natural meaning-preserving paraphrases. Chinese: ${chinese}\nReference pinyin: ${pinyin}\nReference ${languageName(language)}: ${translation}\nLearner: ${answer}\nWrite feedback only in ${languageName(language)} and never include Chinese characters or pinyin in feedback. Return JSON only: {"correct":true,"pinyin":"...","correction":null,"feedback":"Correct."}`;
export const evaluateChinesePrompt = (language: AppLanguage, chinese: string, pinyin: string, translation: string, answer: string) => `Evaluate a learner's Chinese translation of a ${languageName(language)} sentence. Accept natural meaning-preserving Chinese alternatives. ${languageName(language)}: ${translation}\nReference Chinese: ${chinese}\nReference pinyin: ${pinyin}\nLearner Chinese: ${answer}\nWrite feedback in ${languageName(language)}. correction must be the correct Chinese sentence without spaces when incorrect, otherwise null. Return JSON only.`;
export const explainPrompt = (language: AppLanguage, chinese: string, vocabulary: unknown) => `Explain this Mandarin sentence concisely to a ${languageName(language)}-speaking learner. Chinese: ${chinese}\nKnown vocabulary JSON: ${JSON.stringify(vocabulary)}\nThe russian field is a legacy field name: put the ${languageName(language)} translation in it. All explanations and meanings must be in ${languageName(language)}. Return JSON only: {"pinyin":"...","russian":"...","words":[{"word":"今天","meaning":"...","characters":[{"character":"今","meaning":"..."}]}],"grammar":"..."}`;
export const translateWordsPrompt = (language: AppLanguage, words: string[]) => `Translate these Mandarin vocabulary items into ${languageName(language)}: ${JSON.stringify(words)}. Preserve each hanzi value exactly. Give standard Hanyu Pinyin with tone marks and a concise dictionary-style translation. Return every requested item exactly once. Return JSON only: {"words":[{"hanzi":"你好","pinyin":"nǐ hǎo","translation":"hello"}]}`;
