import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors } from './theme';

export function Header({ eyebrow, title, subtitle }: { eyebrow?: string; title: string; subtitle?: string }) { return <View style={s.header}>{eyebrow && <Text style={s.eyebrow}>{eyebrow}</Text>}<Text style={s.title}>{title}</Text>{subtitle && <Text style={s.subtitle}>{subtitle}</Text>}</View>; }
export function Button({ label, onPress, icon, secondary, disabled }: { label: string; onPress: () => void; icon?: keyof typeof Ionicons.glyphMap; secondary?: boolean; disabled?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, secondary && s.secondary, (pressed || disabled) && { opacity: .55 }]}>{icon && <Ionicons name={icon} size={18} color={secondary ? colors.green : colors.white} />}<Text style={[s.buttonText, secondary && { color: colors.green }]}>{label}</Text></Pressable>; }
export const shell = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.paper }, content: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingHorizontal: 22, paddingBottom: 40 }, panel: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, borderRadius: 18, padding: 18 } });
const s = StyleSheet.create({ header: { paddingTop: 28, paddingBottom: 24 }, eyebrow: { color: colors.coral, fontSize: 12, letterSpacing: 1.8, fontWeight: '800', textTransform: 'uppercase', marginBottom: 7 }, title: { fontSize: 34, lineHeight: 39, fontWeight: '800', color: colors.ink, letterSpacing: -.8 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8 }, button: { minHeight: 50, borderRadius: 14, paddingHorizontal: 19, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, secondary: { backgroundColor: colors.pale, borderWidth: 1, borderColor: '#CCDCD1' }, buttonText: { color: colors.white, fontWeight: '700', fontSize: 15 } });
